### PR TITLE
Allow empty dataset if datadict is none

### PR DESCRIPTION
**Pull request by Akshita07**
Hello,

This PR solves the error seen (added below) by experimentalists while live plotting with plottr when a new measurements with qcodes start and there is some unexpected delay in data arrival in the dataset.

Expected behaviour:
A new plot window should appear as soon as a new measurement starts and should be refreshed with the data as it becomes available (with set refresh rate).

Observed behaviour:
Following error is seen on the console due to an unexpected delay on availability of data on the newly created dataset from the new measurements. Once this error occurs, it keeps repeating and the plot window is not refreshed with the data. 

```python
2021-02-09 12:58:29,736 ¦ plottr.data.qcodes_dataset.QCodesDSLoader.Data loader ¦ ERROR ¦ node ¦ update ¦ 227 ¦ EXCEPTION RAISED: <class 'AssertionError'>: 
 ->   File "c:\users\qt2\miniconda3\envs\qc_current\lib\site-packages\pyqtgraph-0.11.0rc0-py3.7.egg\pyqtgraph\flowchart\Node.py", line 303, in update 
    out = self.process(**strDict(vals)) 

 ->   File "c:\users\qt2\miniconda3\envs\qc_current\lib\site-packages\plottr\data\qcodes_dataset.py", line 298, in process 
    data = ds_to_datadict(self._dataset) 

 ->   File "c:\users\qt2\miniconda3\envs\qc_current\lib\site-packages\plottr\data\qcodes_dataset.py", line 245, in ds_to_datadict 
    ddict = combine_datadicts(*[v for k, v in ddicts.items()]) 

 ->   File "c:\users\qt2\miniconda3\envs\qc_current\lib\site-packages\plottr\data\datadict.py", line 1291, in combine_datadicts 
    assert ret is not None
```

Steps to reproduce:
1. Introduce a delay in measurment.py file in qcodes source code on line 558 (just before setting interdependencies)
2. Open plottr load the database and set refresh rate less than delay added in step 1. Check autoplot new.
3. Run a new dummy measurement from the jupyter notebook. 

Proposed solution:
Allow creation of an empty dataset when datadict is None.
Through this solution I do not see any error on the console but the new plot window still doesn't refresh with the data. It remains empty.

@wpfff It will be great if you could help out in figuring out why the plot window is not refreshing with the data. Thank you.
 
Update:
Issue #197 has been created to be resolve later in another PR. The issue deals with new plot window created with empty datadict not refreshing even when the data becomes available on dataset.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
@Akshita07 @astafan8 @wpfff  While this does not fully resolve the issue I think we should still merge it as is and then create a new issue for fixing the rest. Thoughts ?

**Comment by astafan8** [comment]
> While this does not fully resolve the issue I think we should still merge it as is and then create a new issue for fixing the rest

i agree! thanks for suggesting @jenshnielsen . @Akshita07 do you agree?

if we go that way, to make things easier, @Akshita07 , the "new" issue (of the refresh not working on empty dataset) could be extracted into a GitHub issue, and the description of this PR can refer to that as "to be solved later", and then we can merge this PR, and worry about the "refresh" later in that new GitHub issue.

**Comment by Akshita07** [comment]
@jenshnielsen @astafan8 Yes, I agree with the proposed idea. I'll create a new issue and refer it in the description of this PR.

**Review by jenshnielsen — APPROVED** [review]

**Comment by Akshita07** [comment]
@jenshnielsen I do not have merge rights on this repo. Could you please merge it.

**Comment by jenshnielsen** [comment]
The remaining part will be tackled as part of https://github.com/toolsforexperiments/plottr/issues/197

**Pull request merged**
