### PR TITLE
Drop python 3.7 support and Typecheck with Pandas stubs

### PR DESCRIPTION
**Pull request by jenshnielsen**
This adds pandas types and fixes two issues required to typecheck with them.

One is not potentially passing None to a method that does not take None
The other is a workaround for not being able to infer a precise type for a dataframe converted to dict

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Pandas 1.4 only supports python 3.8 and up. Perhaps we should drop support for 3.7 or just drop type checking with 3.7 ?

**Comment by astafan8** [comment]
> drop support for 3.7 

vote for this

**Comment by jenshnielsen** [comment]
@wpfff How do you feel about dropping support for 3.7

The main motivation is that Pandas, numpy, xarray etc have already dropped it making it more annoying to support it here. QCoDeS will drop support soon

**Comment by wpfff** [comment]
Yep, we should drop it. Haven't seen anything below 3.9 in use in a while myself...

**Comment by jenshnielsen** [comment]
@astafan8 Dropped python 3.7 and make it ready for review

**Review by astafan8 — APPROVED** [review]

**Pull request merged**
