### PR TITLE
Adding the AppManager. Still missing GUI.

### LINKED ISSUE #228: launcher script that can be used to liveplot a single measurement without monitr

### PR DESCRIPTION
**Pull request by pfafflabatuiuc**
Adding a new version of the AppManager, used to manage and communicate with apps running in different QProcesses. You can send messages to the apps to change the parameters that live inside of them.

For more information on how it works, check the correct docstrings.

The AppManager has been tested in linux and windows.

### CODE REVIEW

**Comment by marcosfrenkel** [comment]
I have added an issue to be close with this PR. Another 2 open issues that are related but I am not sure if they should be closed:

https://github.com/toolsforexperiments/plottr/issues/205

https://github.com/toolsforexperiments/plottr/issues/91 -> This one seems to be very similar to issue #228 but with extra features (like logging) Those are not yet implemented in the launching script. I have opened another issue to add logging and a way to see the messages the other app is showing. When opening an app from the script itself from terminal, you can see the messages it sends

**Comment by marcosfrenkel** [comment]
The mypy error is a known issue with python 3.10.7 and mypy. There is a solution coming but the work around is to downgrade to python 3.10.6 for now: https://github.com/python/mypy/issues/13627

I don't know how (or even if I can) reconfigure the automatic testing to do that.

**Comment by jenshnielsen** [comment]
@marcosfrenkel mypy 0.981 is out and https://github.com/toolsforexperiments/plottr/pull/331 will fix this

**Review by wpfff — APPROVED** [review]
as discussed in the lab -- looks good!

**Pull request merged**
