### PR TITLE
Make the .gitignore proper

### PR DESCRIPTION
**Pull request by astafan8**

### CODE REVIEW

**Review by wpfff — COMMENTED** [review]
@astafan8 why would you not want to ignore .db files?
I had added that mostly to make sure to not accidentally commit .db files generated during tests.

**Comment by astafan8** [comment]
> why would you not want to ignore .db files? I had added that mostly to make sure to not accidentally commit .db files generated during tests.

@wpfff it's a matter of taste. If db files are generated from the automated tests, then i'd implement a fixture that creates a temporary db file and removes it after the test - hence the repo will not be polluted, and no need to ignore the db files.

My own understanding of gitignore is that it's meant to ignore files which inevitably end up in the repo during development/execution of the code only. For all the other junk, its the developer's responsibility to not commit that accidentally and keep an eye on what's changed in the repo.

If you don't share this approach, no problem, i can add the ignore entries for the db files.

**Comment by jenshnielsen** [comment]
Is this still something that we would like to merge? Is there a good reason to exclude the docs make files

**Comment by astafan8** [comment]
> Is there a good reason to exclude the docs make files

no, that's probably a mistake.

> Is this still something that we would like to merge?

i'd say, totally! :) once it's "correct"

**Comment by wpfff** [comment]
remind me -- what's missing for it be 'correct' now :) 
(i can't see the thing i was wondering about back then anymore)

**Comment by jenshnielsen** [comment]
@wpfff There was a discusion about if we should exclude .db files. Thats the only thing I can think of

**Comment by astafan8** [comment]
@wpfff shall we merge this? it requires your approval :) db file are ignored now

**Review by wpfff — APPROVED** [review]

**Comment by wpfff** [comment]
forgot, sorry :)

**Pull request merged**
